["Science Building",
"Bernard P. McDonough Hall",
"Building D",
"Bunn Intercultural Center",
"Car Barn",
"Chapel of St. Thomas More",
"Concentrated Care Center",
"Georgetown University Hospital",
"Cooper Field",
"Georgetown Hoyas",
"Copley Crypt Chapel of the North American Martyrs",
"Dahlgren Chapel of the Sacred Heart",
"Davis Performing Arts Center",
"Gonda Theater",
"Royden B. Davis",
"Edmund A. Walsh School of Foreign Service",
"Edward Bennett Williams Law Library",
"Eric E. Hotung International Law Center",
"John Wolff International and Comparative Law Library",
"Georgetown University Law Center",
"Gervase Building",
"Gewirz Student Center",
"Gorman Building",
"GUQ Building",
"Education City",
"Healy Hall",
"Gaston Hall",
"Riggs Library",
"National Historic Landmark",
"Institute of Diplomacy",
"John Vinton Dahlgren Medical Library",
"Kehoe Field",
"Georgetown Hoyas",
"Kober Cogan Building",
"Lauinger Library",
"Leavey Center",
"Students of Georgetown, Inc.",
"WGTB",
"Georgetown University Alumni & Student Federal Credit Union",
"Leo J. O'Donovan Dining Hall",
"Liberal Arts and Science Building",
"Georgetown University School of Foreign Service in Qatar",
"Lombardi Cancer Center",
"Vince Lombardi",
"Maguire Hall",
"Marcus Bles Building",
"McDonough Gymnasium",
"Georgetown Hoyas",
"Dwight D. Eisenhower",
"McGhee Center for Eastern Mediterranean Studies",
"Alanya",
"McSherry Building",
"Medical and Dental Annex",
"Medical and Dental Building",
"Mortara Center For International Studies",
"Mulledy Building",
"New North",
"New Research Building",
"Georgetown University Observatory",
"National Register of Historic Places",
"Old North",
"McCourt School of Public Policy",
"Pasquerilla Healthcare Center",
"Ferdinand Poulton",
"Pre-Clinical Science Building",
"Rafik B. Hariri Building",
"Reed Alumni Residence",
"Regents Hall",
"Reiss Science Building",
"Research Resource Facility",
"Georgetown University Medical Center",
"Southwest Quadrangle",
"Robert and Bernice Wagner Alumni House",
"Ryan Hall",
"Woodstock Theological Center",
"Georgetown Law Sport and Fitness Center",
"Georgetown Hoyas",
"St. Mary's Hall",
"St. William's Chapel",
"Villa Le Balze",
"Fiesole",
"White-Gravenor Hall",
"Andrew White",
"Wolfington Hall Jesuit Residence",
"Yates Field House"]